<?php
define('_search','search for'); 
define('_dashboard','DASHBOARD');
define('_account','CLIENT ACCOUNT');
define('_invoice','INVOICE');
define('_document','DOCUMENTS');
define('_my_bills','MY BILLS');
define('_my_account','MY ACCOUNTS');
define('_admin','ADMIN');
define('_settings','Settings');
define('_changa_password','Change Password');
define('_logout','Logout');
define('_create_account','CREATE A CLIENT');
define('_edit_account','EDIT A CLIENT');
define('_delete_account','REMOVE A CLIENT');
define('_view_invoice','VIEW AN INVOICE');
define('_view_document','VIEW DOCUMENTS');
define('_photo_upload','UPLOAD PHOTO');
define('_name','NOM');
define('_surname','SURNAME');
define('_email','EMAIL');
define('_phone','PHONE');
define('_company','COMPANY');
define('_position','POSITION');
define('_address','ADDRESS');
define('_city','CITY');
define('_create_invoice','CREATE AN INVOICE');
define('_edit_invoice','EDIT AN INVOICE');
define('_paid','PAID');
define('_not_paid','WITHOUT PAY');
define('_amount','AMOUNT1');
define('_amount2','AMOUNT2');
define('_new_client','New Client');
define('_select_client','Select Client');
define('_upload_document','UPLOAD DOCUMENT');
define('_add_client_success','The client been added correctly');
define('_delete_client_success','The Client Removed Correctly');
define('_ch_pass','Change Password');
define('_old_pass','OLD PASSWORD');
define('_new_pass','NEW PASSWORD');
define('_con_pass','CONFIRM PASSWORD');
define('_setting','SETTINGS');
define('_client_invoice','ADD NEW INVOICE TO THIS ClIENT');
define('_list_client_invoice','LIST OF CLIENT INVOICES');
define('_client_info','CLIENT INFORMATION');
define('_Appartement','Appartement');
define('_Situation','Situation');
define('_Tarifs','Tarifs');
define('_Services','Services');
define('_business','Business');
define('_Contact','Contact Us');
define('_welcome','Welcome');
define('_creating_account','CREATING A CLIENT');
define('_editing_account','UPDATE A CLIENT');
define('_creating_invoice','CREATING AN INVOICE');
define('_editing_invoice','UPDATE AN INVOICE');
define('_save','Save');

define('_document','DOCUMENT');
define('_create_document','Enregistrer');
define('_edit_document','Enregistrer');
define('_creating_document','Enregistrer');
define('_editing_document','Enregistrer');

define('_welcome_index1','Welcome to the');
define('_welcome_index2','client area of the');
define('_welcome_index3','Residence');
define('_welcome_index4','Paris Asnieres');
define('_back_to_login','Back to Login');

define('_i_account','create an account');
define('_lost_pass','lost password');
define('_client_title','Your Customer Area');
define('_client1','Dear Client, Dear Customer,');
define('_client2','You are on the customer area of our residence.');
define('_client3','You can view your bills and history. Each time line of an invoice, you will receive an email for information.');
define('_client4','You can also make your payment by credit card through our secure module.');
define('_client5','In case of problems, do not hesitate to contact us on 01 40 86 12 19.');

?>