<?php
define('_search','Rechercher'); 
define('_dashboard','TABLEAU DE BORD');
define('_account','COMPTE CLIENT');
define('_invoice','FACTURES');
define('_document','DOCUMENTS');
define('_my_bills','MES FACTURES');
define('_my_account','MON COMPTE');
define('_admin','ADMIN');
define('_settings','paramètres');
define('_changa_password','changer le mot de passe');
define('_logout','Déconnexion');
define('_create_account','CREATION UN COMPTE');
define('_edit_account','MODIFIER COMPTE');
define('_delete_account','Supprimer un client');
define('_view_invoice','VISUALISER LES FACTURES');
define('_view_document','VISUALISER LES DOCUMENTS');
define('_photo_upload','Télécharger une photo');
define('_name','NOM');
define('_surname','PRENOM');
define('_email','E-MAIL');
define('_phone','TEL');
define('_company','SOCIETE');
define('_position','POSTE');
define('_address','ADRESSE');
define('_city','VILLE');
define('_create_invoice','Ajouter une facture');
define('_dis_create_invoice','AJOUTER UNE FACTURE');
define('_paid','PAYÉ');
define('_edit_invoice','éditer une facture');
define('_not_paid_not_paid','NON PAYÉ');
define('_amount','MONTANT1');
define('_amount2','MONTANT2');
define('_new_client','nouveau client');
define('_select_client','Sélectionnez Client');
define('_upload_document','Télécharger le document');
define('_add_client_success','Le client a été ajouté correctement');
define('_delete_client_success','Le client de les ôter correctement');
define('_ch_pass','changer le mot de passe');
define('_old_pass','ancien mot de passe');
define('_new_pass','nouveau mot de passe');
define('_con_pass','Confirmez le mot de passe');
define('_setting','REGLAGES');
define('_client_invoice','Ajouter nouvelle facture à ce client');
define('_list_client_invoice','LISTE DES FACTURES CLIENTS');
define('_client_info','INFORMATIONS CLIENT');
define('_Appartement','Appartement');
define('_Situation','Situation');
define('_Tarifs','Tarifs');
define('_business','entreprise');
define('_Contact','Contactez-nous');
define('_welcome','accueil');
define('_creating_account',"CREATION D'UN COMPTE");
define('_editing_account','JOUR UN COMPTE');
define('_creating_invoice',"Ajouter la facture");
define('_editing_invoice','éditer la facture');
define('_Services','Services');
define('_save','Enregistrer');

define('_document','DOCUMENT');
define('_create_document','Créer un document');
define('_edit_document','Modifier le document');
define('_creating_document',"création d'un document");
define('_editing_document',"l'édition de documents");

define('_welcome_index1','Bienvenue sur');
define('_welcome_index2','l’espace client de la');
define('_welcome_index3','Résidences');
define('_welcome_index4','Paris Asnières');
define('_back_to_login','Retour à la connexion');

define('_i_account','créer un compte');
define('_lost_pass','mot de passe perdu');
define('_client_title','Votre Espace Client');
define('_client1','Chère Cliente, Cher Client,');
define('_client2','Vous êtes sur l’espace client de notre résidence.');
define('_client3','Vous pouvez y consulter vos factures et leur historique. A chaque mise en ligne d’une facture, vous recevez un email d’information. ');
define('_client4','Vous pouvez également effectuer vos règlements par carte bancaire par l’intermédiaire de notre module sécurisé.');
define('_client5','En cas de problème, n’hésitez pas à nous contacter au 01 40 86 12 19.');
?>